name = "SteadyState"
uuid = "c1b8730e-8541-11e9-355e-9f44ccd93e35"
authors = ["Z-Denis <zakari.denis@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
